[google_oauth]
client_id = "297303618465-turalep9dm3r802h67185eqv35jg750j.apps.googleusercontent.com"
client_secret = "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"
redirect_uri = "http://localhost:8501"
auth_uri = "https://accounts.google.com/o/oauth2/v2/auth"
token_uri = "https://oauth2.googleapis.com/token"
